# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 60dcaef22a3e6edcc2a6d0e85f4c72d16229c218dbbd7228f46b4f799004b4fc76c82fd6bdeec70586c6dcf3271606160b59410a23a560f3f792703326500b86

test:
  secret_key_base: 98de3dd8356f5ba8e159c5646193c7925ff729d936d061aa38a5b1b4a8c2ee936f1d4273b2876c5cf7a413b947fee73343f1030b01110364c3a3146e4ff9af47

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
